# **(학습) Python Pandas 완벽 마스터 학습 노트**

## **📖 Part 1: pandas 입문**

### 🔍 핵심 개념

#### 1️⃣ 데이터과학자가 pandas를 배우는 이유

**핵심 포인트**: 빅데이터 시대의 데이터 전처리 필수 도구

**주요 특징:**

- 80~90%의 데이터 수집 및 정리 작업 담당
- 데이터과학의 가장 기초적이고 중요한 도구
- 클라우드 컴퓨팅 환경에서의 필수 프로그래밍 지식

#### 2️⃣ pandas 자료구조
📊 Series (1차원 배열)
- Series는 1차원 배열로 index와 value를 가진다.
- 딕셔너리를 Series로 바로 변환이 가능하며 Key는 index로 Value는 Value로 변환된다.
- class pandas.Series(data=None, index=None, dtype=None, name=None, copy=None, fastpath=<no_default>)

In [1]:
# Series 생성
import pandas as pd

# 딕셔너리로 Series 생성
dict_data = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
sr = pd.Series(dict_data)
print(sr)

# 기본 구조 확인
print(f"인덱스: {sr.index}")
print(f"값: {sr.values}")

a    1
b    2
c    3
d    4
dtype: int64
인덱스: Index(['a', 'b', 'c', 'd'], dtype='object')
값: [1 2 3 4]

### 🔍 구체적인 차이점들

#### 1️⃣ 데이터 접근 방식

In [ ]:
# 리스트: 위치로만 접근 (의미 불분명)
seojun_scores_list = [90, 85, 95]
# 서준이 성적을 Series로
seojun_scores = pd.Series([90, 85, 95],
                         index=['수학', '국어', '영어'])

print(seojun_scores_list[0])# 90 (이게 뭔 과목?)
print(seojun_scores_list[1])# 85 (이것도 뭔 과목?)# Series: 의미있는 라벨로 접근
print(seojun_scores['수학'])# 90 (명확히 수학 점수!)
print(seojun_scores['국어'])# 85 (명확히 국어 점수!)

90
85
90
85

#### 2️⃣ 데이터 분석 편의성

In [5]:
# 리스트: 수동으로 계산
total = sum(seojun_scores_list)
average = total / len(seojun_scores_list)
print(f"평균: {average}")

# Series: 내장 함수 활용
print(f"평균: {seojun_scores.mean()}")
print(f"최고점: {seojun_scores.max()}")
print(f"최고 과목: {seojun_scores.idxmax()}")# 최고점인 과목명까지!

평균: 90.0
평균: 90.0
최고점: 95
최고 과목: 영어

#### 3️⃣ 조건 필터링

In [6]:
# 리스트: 복잡한 과정
high_scores_list = []
for i, score in enumerate(seojun_scores_list):
    if score >= 90:
# 어떤 과목인지 별도로 관리해야 함
        subjects = ['수학', '국어', '영어']
        high_scores_list.append((subjects[i], score))

# Series: 간단하고 직관적
high_scores = seojun_scores[seojun_scores >= 90]
print("90점 이상 과목:")
print(high_scores)

90점 이상 과목:
수학    90
영어    95
dtype: int64

## 🔧 Part 2: 핵심 기능 정리

### 🏷️ 인덱스 활용

#### 1.Series 인덱스

In [7]:
# 인덱스 설정
print(sr.index)

# 데이터 값 배열
print(sr.values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[1 2 3 4]

#### 2.DataFrame 인덱스/열 이름 설정

In [9]:
# 배열로 DataFrame 생성 시 행 인덱스/열 이름 설정
data_array = [[90, 98, 85], [80, 89, 95], [70, 95, 100]]
df_custom = pd.DataFrame(data_array,
                        index=['서준', '우현', '인아'],
                        columns=['수학', '영어', '음악'])
print(df_custom)

    수학  영어   음악
서준  90  98   85
우현  80  89   95
인아  70  95  100

# **미션**

## 📖 Part 1: 판다스 기초

### **🔥 미션 1-1**  
판다스를 설치하고 임포트한 후, 판다스 버전을 확인해보세요.

In [ ]:
# 여기에 코드를 작성하세요
import pandas as pd

# 버전 확인
print(pd.__version__)

2.3.3

### **🔥 미션 1-2**
다음 학생들의 점수 데이터로 Series를 만들어보세요.

- 김철수: 85점, 이영희: 92점, 박민수: 78점, 최지연: 96점

In [ ]:
data = {"김철수": 85, "이영희" : 92, "박민수":78, "최지연" :96}
s = pd.Series(data)
s

김철수    85
이영희    92
박민수    78
최지연    96
dtype: int64

### **🔥 미션 1-3 (심화)**
위에서 만든 Series에서:

1. 이영희의 점수를 출력하세요
2. 90점 이상인 학생들을 필터링하세요
3. 모든 점수에 5점을 더해보세요

In [ ]:
#1
print(s["이영희"])

#2
score = s[s >=90]
score.index

#3
s+=5
print(s)

92
김철수     90
이영희     97
박민수     83
최지연    101
dtype: int64

## 📊 Part 2: DataFrame 마스터하기

### **🔥 미션 2-1**
다음 학생 정보로 DataFrame을 생성하세요:
| 이름 | 나이 | 성별 | 점수 |
|---|---|---|---|
| 김철수 | 20 | 남 | 85 |
| 이영희 | 19 | 여 | 92 |
| 박민수 | 21 | 남 | 78 |
| 최지연 | 20 | 여 | 96 |

**📝 학습 내용**

- DataFrame은 2차원 표 형태의 자료구조
- 행(row)과 열(column)으로 구성
- 여러 Series가 결합된 형태

In [ ]:
data2 = {
        "이름": ["김철수","이영희","박민수","최지연"],
        "나이": [20,19,21,20],
        "성별": ["남","여","남","여"],
        "점수": [85,92,78,96]
}

df = pd.DataFrame(data2)
df

    이름  나이 성별  점수
0  김철수  20  남  85
1  이영희  19  여  92
2  박민수  21  남  78
3  최지연  20  여  96

###**🔥 미션 2-2**
생성한 DataFrame에서:

1. 기본 정보를 확인하세요 (info(), describe(), shape)
2. 첫 2행을 출력하세요
3. '점수' 열만 선택해서 출력하세요

In [ ]:
#1 기본 정보를 확인하세요 (info(), describe(), shape)
df.info()

df.describe()

df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      object
 1   나이      4 non-null      int64
 2   성별      4 non-null      object
 3   점수      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

(4, 4)

In [ ]:
#2 첫 2행을 출력하세요
df.head(2)

    이름  나이 성별  점수
0  김철수  20  남  85
1  이영희  19  여  92

In [ ]:
#3 '점수' 열만 선택해서 출력하세요

In [ ]:
print(df["점수"]) #Series 형태 출력

print(df[["점수"]]) #DataFrame 형태 출력(열 이름 유지)

0    85
1    92
2    78
3    96
Name: 점수, dtype: int64
   점수
0  85
1  92
2  78
3  96

## 🔍 Part 3: 데이터 조작과 필터링
**📝 학습 내용**

- loc: 라벨 기반 인덱싱
-> 이름(인덱스 또는 조건)을 기준으로 한 사람의 모든 정보를 출력할 수 있다.
- iloc: 위치 기반 인덱싱
- 조건부 필터링

### **🔥 미션 3-1**

위에서 만든 student DataFrame에서:

1. loc을 사용해서 이영희의 모든 정보를 출력하세요
2. iloc을 사용해서 첫 번째와 세 번째 행의 '이름'과 '점수'를 출력하세요
3. 나이가 20살인 학생들을 필터링하세요

In [ ]:
#1 loc을 사용해서 이영희의 모든 정보를 출력하세요
df.loc[df["이름"] == "이영희"]

    이름  나이 성별  점수
1  이영희  19  여  92

In [ ]:
#2 iloc을 사용해서 첫 번째와 세 번째 행의 '이름'과 '점수'를 출력하세요

df.iloc[[0,2],[0,3]]
# 0,2 -> 첫번째와 세번째 행 인덱스
# 0,3 -> 이름과 점수의 컬럼 인덱스

    이름  점수
0  김철수  85
2  박민수  78

In [ ]:
#3 나이가 20살인 학생들을 필터링하세요
df.loc[df["나이"] == 20]

    이름  나이 성별  점수
0  김철수  20  남  85
3  최지연  20  여  96

### **🔥 미션 3-2**

1. 새로운 학생 '정민호(22세, 남, 88점)'를 추가하세요
2. 모든 학생의 점수에 3점을 더하세요
3. '등급' 열을 추가하세요 (90점 이상: A, 80-89점: B, 80점 미만: C)

In [ ]:
#1 새로운 학생 '정민호(22세, 남, 88점)'를 추가하세요

df.loc[len(df)] =["정민호",22,"남",88]

In [ ]:
#2 모든 학생의 점수에 3점을 더하세요
df["점수"] += 3

In [ ]:
df

    이름  나이 성별  점수 등급
0  김철수  20  남  88  B
1  이영희  19  여  95  A
2  박민수  21  남  81  B
3  최지연  20  여  99  A

In [ ]:
#3 '등급' 열을 추가하세요 (90점 이상: A, 80-89점: B, 80점 미만: C)

#df["등급"] = ["B","A","C","A"]
#값을 넣어서 열을 추가하는 방법

# 함수를 작성 후 apply 사용 방법
def get_grade(점수):
    if 점수 >=90:
        return "A"
    elif 점수 >=80:
        return "B"
    else:
        return "C"

df["등급"] = df["점수"].apply(get_grade)

In [ ]:
df

    이름  나이 성별  점수 등급
0  김철수  20  남  88  B
1  이영희  19  여  95  A
2  박민수  21  남  81  B
3  최지연  20  여  99  A
4  정민호  22  남  88  B

## 📈 Part 4: 실전 데이터 분석

### **🔥 미션 4-1 (종합 프로젝트)**
다음 온라인 쇼핑몰 판매 데이터를 분석해보세요:

**요구사항:**

1. 총 매출액을 계산하세요 (가격 × 수량)
2. 고객별 주문 횟수와 총 구매금액을 구하세요
3. 가장 많이 팔린 상품을 찾으세요
4. 일별 매출 현황을 분석하세요
5. 10만원 이상 구매한 주문만 필터링하세요

In [ ]:
import pandas as pd

# 샘플 데이터 생성
sales_data = {
    '주문번호': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005', 'ORD006'],
    '고객명': ['김철수', '이영희', '박민수', '김철수', '최지연', '이영희'],
    '상품명': ['노트북', '마우스', '키보드', '모니터', '노트북', '스피커'],
    '가격': [1200000, 25000, 80000, 300000, 1350000, 120000],
    '수량': [1, 2, 1, 1, 1, 1],
    '주문일': ['2024-01-15', '2024-01-16', '2024-01-16', '2024-01-17', '2024-01-17', '2024-01-18']
}

df_sales = pd.DataFrame(sales_data)
df_sales

     주문번호  고객명  상품명       가격  수량         주문일
0  ORD001  김철수  노트북  1200000   1  2024-01-15
1  ORD002  이영희  마우스    25000   2  2024-01-16
2  ORD003  박민수  키보드    80000   1  2024-01-16
3  ORD004  김철수  모니터   300000   1  2024-01-17
4  ORD005  최지연  노트북  1350000   1  2024-01-17
5  ORD006  이영희  스피커   120000   1  2024-01-18

In [ ]:
#1 총 매출액을 계산하세요 (가격 × 수량)

df_sales["가격"]*df_sales["수량"]
total = (df_sales["가격"]*df_sales["수량"]).sum()
total

np.int64(3100000)

In [ ]:
#2 고객별 주문횟수와 총 구매금액을 구하세요
# 고객별 주문횟수
# df_sales.groupby("고객명")["주문번호"].count()

df_sales["주문량"] = df_sales["가격"] * df_sales["수량"]


#agg를 사용하여 컬럼마다 다른 집계 적용할 수 있음
# 주문번호에는 count, 주문량 sum
result = df_sales.groupby("고객명").agg(
    order_count=("주문번호", "count"),
    total_purchase=("주문량", "sum"))


result

     order_count  total_purchase
고객명
김철수            2         1500000
박민수            1           80000
이영희            2          170000
최지연            1         1350000

In [ ]:
#3 가장 많이 팔린 상품을 찾으세요

#답이 노트북, 마우스 2개가 나와야할 것 같은데 왜 노트북만 나올까...
#max()는 얼마나, idxmax()는 누가
df_sales.groupby("상품명")["수량"].sum().idxmax()

'노트북'

In [ ]:
#4 일별 매출 현황을 분석하세요

# to_datetime : 문자열이나 숫자로 된 날짜데이터를
# datetime 타입으로 바꿔서 날짜 연산을 가능하게 해줌
#df_sales["주문일"] = pd.to_datetime(df_sales["주문일"])

#주문별 매출
df_sales["판매"] = df_sales["가격"] * df_sales["수량"]

#일자별 집계
daily = df_sales.groupby("주문일").agg(
    order_count=("주문번호", "count"),          # 주문 건수
    total_quantity=("수량", "sum"),            # 판매 수량 합
    total_sales=("판매", "sum"),               # 총 매출
    unique_customers=("고객명", "nunique"),    # 구매 고객 수( nunique 중복 제거)
).reset_index()

print(daily)

         주문일  order_count  total_quantity  total_sales  unique_customers
0 2024-01-15            1               1      1200000                 1
1 2024-01-16            2               3       130000                 2
2 2024-01-17            2               2      1650000                 2
3 2024-01-18            1               1       120000                 1

In [ ]:
#5 10만원 이상 구매한 주문만 필터링하세요

df_sales[df_sales["가격"]*df_sales["수량"] > 100000]

     주문번호  고객명  상품명       가격  수량        주문일      주문량       판매
0  ORD001  김철수  노트북  1200000   1 2024-01-15  1200000  1200000
3  ORD004  김철수  모니터   300000   1 2024-01-17   300000   300000
4  ORD005  최지연  노트북  1350000   1 2024-01-17  1350000  1350000
5  ORD006  이영희  스피커   120000   1 2024-01-18   120000   120000

## 🎯 추가 심화 미션

### **심화 미션1: 결측치 처리**
다음 데이터에서 결측치를 처리해보세요

**요구사항:**

1. 결측치가 있는 행과 열을 확인하세요
2. 나이의 결측치는 평균값으로 채우세요
3. 점수의 결측치는 중앙값으로 채우세요

In [ ]:
import numpy as np

# 결측치가 있는 데이터
# 결측치란 관측되거나 입력되어야 할 데이터가 비어 있거나 존재하지 않는 값
# 대표적인 형태 NaN(Not a Number) / None / NaT 날짜, 시간 결측치

messy_data = {
    '이름': ['A', 'B', 'C', 'D', 'E'],
    '나이': [25, np.nan, 30, 28, np.nan],
    '점수': [85, 90, np.nan, 95, 88]
}

df_messy = pd.DataFrame(messy_data)
df_messy

  이름    나이    점수
0  A  25.0  85.0
1  B   NaN  90.0
2  C  30.0   NaN
3  D  28.0  95.0
4  E   NaN  88.0

In [ ]:
#1 결측치가 있는 행과 열을 확인하세요
# isnull : 결측치 True, 정상값 False

df_messy.isnull()

      이름     나이     점수
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [ ]:
#2 나이의 결측치는 평균값으로 채우세요
#평균을 계산 후 반올림하여 평균값으로 채움

df_messy["나이"]=df_messy["나이"].fillna(df_messy["나이"].mean().round())
display(df_messy)

  이름    나이    점수
0  A  25.0  85.0
1  B  28.0  90.0
2  C  30.0   NaN
3  D  28.0  95.0
4  E  28.0  88.0

In [ ]:
#3 점수의 결측치는 중앙값으로 채우세요


df_messy["점수"] = df_messy["점수"].fillna(df_messy["점수"].median())
display(df_messy)

  이름    나이    점수
0  A  25.0  85.0
1  B  28.0  90.0
2  C  30.0  89.0
3  D  28.0  95.0
4  E  28.0  88.0

### **심화 미션 2 : 데이터 병합**
두 개의 DataFrame을 병합해보세요

**요구사항:**

1. 두 DataFrame을 학번을 기준으로 병합하세요
2. 각 학생의 평균 점수를 계산하세요

In [ ]:
# 학생 기본정보
students = pd.DataFrame({
    '학번': ['S001', 'S002', 'S003'],
    '이름': ['김철수', '이영희', '박민수'],
    '학과': ['컴퓨터공학', '통계학', '경영학']
})

# 학생 성적정보
scores = pd.DataFrame({
    '학번': ['S001', 'S002', 'S003'],
    '수학': [85, 92, 78],
    '영어': [88, 85, 90]
})

display(students)
display(scores)

     학번   이름     학과
0  S001  김철수  컴퓨터공학
1  S002  이영희    통계학
2  S003  박민수    경영학

     학번  수학  영어
0  S001  85  88
1  S002  92  85
2  S003  78  90

In [ ]:
# 기본정보
students = pd.DataFrame({
    '학번': ['S001', 'S002', 'S003'],
    '이름': ['김철수', '이영희', '박민수'],
    '학과': ['컴퓨터공학', '통계학', '경영학']
})

# 성적정보
scores = pd.DataFrame({
    '학번': ['S001', 'S002', 'S003'],
    '수학': [85, 92, 78],
    '영어': [88, 85, 90]
})

# 병합
merged = pd.merge(students, scores, on='학번')

# 평균 점수 계산
merged['평균'] = merged[['수학', '영어']].mean(axis=1)
print(merged)